blank_issues_enabled: true
contact_links:
  - name: ğŸ“š DocumentaciÃ³n del Proyecto
    url: https://github.com/Josojmf/AI_Firefighter/wiki
    about: Consulta la documentaciÃ³n tÃ©cnica y guÃ­as de uso
  - name: ğŸ’¬ Discusiones y Preguntas
    url: https://github.com/Josojmf/AI_Firefighter/discussions
    about: Haz preguntas o participa en discusiones
